### ISSUE TITLE
option for no output

### ISSUE THREAD

**Issue by ekjaker** [sbarakat/beets-copyartifacts#21]
Hi,

I've been using copy-artifacts, works like a charm. So much so that I trust it enough to not need the output for every successful copy. Thing is, this output often disturbs the regular output of beets, making it a lot more difficult to go through the importer.
Would it be possible to add an option, similar to the ```print_ignored``` option, that also allows the choice to have regular output, or more importantly, no output at all? Maybe ```print_successful```?

thx!

**Comment by sbarakat** [comment]
Hey @ekjaker, great to hear!

Improving the messaging is certainly on the list! When this was first written I wasn't too familiar with beets or it's regular output format, so I just printed what I thought would be useful at the time. Once support for `beet move` is out the way I'd be happy to revisit the output format and adding more options.

**Comment by ekjaker** [comment]
Thx! Looking forward to it. Seems to be quite a simple addition with a lot of benefit.

**Comment by sbarakat** [comment]
Thanks to @mried's PR, this should be in the next version. It now uses [Beets' logger](http://beets.readthedocs.org/en/v1.3.15/dev/plugins.html#logging) and recommendation of not noisily interrupting the importer.

To bring back this output you can run in verbose mode.

**Comment by ekjaker** [comment]
thx! Nice solution!
