### ISSUE TITLE
crash copying artifacts with invalid characters

### ISSUE THREAD

**Issue by ekjaker** [sbarakat/beets-copyartifacts#24]
beets-copyartifacts crashes when copying artifacts that have invalid characters. This only occurs if a path renaming is required and the ```albumartist``` or ```album``` have invalid characters in the tags.

config file:
```
    ext:log: $albumpath\$albumartist - $album
    ext:LOG: $albumpath\$albumartist - $album
    ext:cue: $albumpath\$albumartist - $album
    ext:CUE: $albumpath\$albumartist - $album
    ext:pdf: $albumpath\$albumartist - $album
    ext:PDF: $albumpath\$albumartist - $album
    ext:nfo: $albumpath\$albumartist - $album
    ext:NFO: $albumpath\$albumartist - $album
```

The example of an error below is quite lengthy, but it is the ```?``` at the end of the path that is causing the issue. I had the same with "De La Soul - It ain't all good?", but not with any other releases.

```
Error: invalid mode ('wb') or filename while copying \\?\d:\Downloads\utorrent\complete E-J\George Clinton & The P-Funk All-Stars - How Late Do U Have 2BB4UR Absent (2005) [FLAC]\Disc 1\How Late Do U Have 2BB4UR Absent.cue to \\?\E:\Audio\beets\FLAC\G\George Clinton Presents P-Funk All Stars\[2005] How Late Do U Have 2BB4UR Absent_\George Clinton Presents P-Funk All Stars - How Late Do U Have 2BB4UR Absent?.cue
```

Should be straightforward to replicate. If needed, I can also provide files. Seems to me beets-copyartifacts needs to apply the same [character-replacement](http://beets.readthedocs.org/en/v1.3.15/reference/config.html#replace) as beets does.

**Comment by sbarakat** [comment]
Thank you for the very detailed bug report! It made fixing this a lot easier. Should be in the next release :)

**Comment by ekjaker** [comment]
Cool! thx.
