### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'_

### ISSUE THREAD

**Issue by avma** [sbarakat/beets-copyartifacts#34]
hi

running bees 1.4.3 , python 3.6.1 on a raspberry pi3, raspbian jessie(light). i'm getting these errors:
 ** error loading plugin copyartifacts:
Traceback (most recent call last):
 

 _File "/usr/local/lib/python3.6/site-packages/beets/plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python3.6/site-packages/beetsplug/copyartifacts.py", line 141
    print 'Ignored files:'
                         ^
SyntaxError: Missing parentheses in call to 'print'_

any idea?
best regards

**Comment by DOFfactory** [comment]
I am running `linuxserver/beets:latest` dockerized container, running python 3.8, and I am receiving the error if I install beets-copyartifacts:

```
** error loading plugin copyartifacts:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/lib/python3.8/site-packages/beetsplug/copyartifacts.py", line 141
    print 'Ignored files:'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Ignored files:')?

error: No matching items found.
```
